const strings = {
  appName: "APMS",
  appFullName: "Academic Project Management System",
  tagline: "Organize · Track · Showcase",
  navbar: {
    toggleMenu: "Toggle navigation menu",
    browse: "Browse",
    dashboard: "Dashboard",
    projects: "Projects",
    kanban: "Kanban",
    tasks: "Tasks",
    technologies: "Technologies",
    team: "Team",
    admin: "Users",
    settings: "Settings",
  },
  auth: {
    login: "Sign In",
    logout: "Sign Out",
    email: "Email address",
    password: "Password",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your APMS account",
    demoAccounts: "Demo accounts",
    loginError: "Invalid email or password",
    domainNotAllowed:
      "Only signups from the esg.ipsantarem.pt domain are allowed.",
    loginButton: "Sign in",
    loggingIn: "Signing in...",
    studentIdHint:
      "Your student ID will be based on your email (e.g. {id}). If that ID is already taken, a number is added automatically.",
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "Overview of your academic projects",
    subtitleOverview: "Overview of {n} projects you can access",
    totalProjects: "Total Projects",
    activeProjects: "Active Projects",
    totalStudents: "Students",
    myOpenTasks: "My open tasks",
    recentProjects: "Recent Projects",
    tasksByStatus: "Tasks by Status",
    quickActions: "Quick Actions",
    newProject: "New Project",
    viewAll: "View all",
  },
  tasks: {
    title: "My tasks",
    subtitle: "{n} open task(s) assigned to you",
    filterProject: "Project",
    filterStatus: "Status",
    allProjects: "All projects",
    allStatuses: "All open",
    emptyTitle: "No open tasks",
    emptyHint: "Tasks assigned to you that are not done will appear here.",
    emptyFilteredTitle: "No tasks match these filters",
    emptyFilteredHint: "Try another project or status, or clear the filters.",
    moveStatus: "Move task to column",
    openInKanban: "Open in Kanban",
  },
  projects: {
    title: "Projects",
    subtitle: "All academic projects",
    subtitleOverview: "All accessible projects",
    new: "New Project",
    search: "Search projects...",
    filter: "Filter",
    noProjects: "No projects found",
    noProjectsHint: "Create your first project to get started",
    status: {
      planning: "Planning",
      active: "Active",
      completed: "Completed",
      archived: "Archived",
    },
    sortBy: "Sort by",
    allStatuses: "All Statuses",
    filterMyMember: "Only projects I'm a member of",
    filterMyCoordinate: "Only projects I coordinate",
    showingCount: "Showing {shown} of {total}",
    showMore: "Show more",
    showMoreCount: "Show {n} more",
    filters: {
      title: "Filters",
      clearAll: "Clear all",
      any: "Any",
      status: "Status",
      semester: "Semester",
      year: "Year",
      teamSize: "Team size",
      visibility: "Visibility",
      technologies: "Technologies",
      techHint: "Select one or more — project must include all chosen technologies",
      memberAny: "Any size",
      memberSmall: "1–2 members",
      memberMedium: "3–5 members",
      memberLarge: "6–10 members",
      memberXLarge: "11+ members",
      sortUpdated: "Recently updated",
      sortCreated: "Recently created",
      sortTitle: "Title A–Z",
    },
    viewDetails: "View Details",
    editProject: "Edit Project",
    deleteProject: "Delete Project",
    confirmDelete: "Are you sure you want to delete this project?",
    confirmDeleteAdmin:
      "Delete this project permanently? All tasks and team links will be removed.",
    deleteError: "Could not delete the project. You may not have permission.",
    tasks: "Tasks",
    members: "Members",
    technologies: "Technologies",
    repository: "Repository",
    demo: "Live Demo",
    visibility: "Visibility",
    public: "Public",
    private: "Private",
    semester: "Semester",
    year: "Year",
    timeline: "Timeline",
    startDate: "Start",
    endDate: "End",
    created: "Created",
    updated: "Last updated",
  },
  kanban: {
    title: "Kanban Board",
    subtitle: "Manage project tasks",
    columns: {
      todo: "To Do",
      "in-progress": "In Progress",
      review: "Review",
      done: "Done",
    },
    noTasks: "No tasks",
    priority: {
      low: "Low",
      medium: "Medium",
      high: "High",
    },
    assignedTo: "Assigned to",
    assignedToYou: "Assigned to you",
    unassigned: "Unassigned",
    due: "Due",
    selectProject: "Select a project to view its kanban board",
    myAssignedTasks: "Show my tasks from all projects",
    subtitleAssigned: "Tasks assigned to you across all projects",
    noAssignedTasks: "No tasks assigned to you",
    noAssignedTasksHint:
      "When you are assigned work on a project, it will appear here.",
    editTask: "Edit task",
    viewTask: "Task details",
    editTaskBtn: "Edit",
    cancelEdit: "Cancel",
    saving: "Saving…",
    saveError: "Failed to save task. Please try again.",
    noDescription: "No description provided.",
    noDueDate: "No due date",
    taskTitle: "Title",
    taskDescription: "Description",
    taskDescriptionPlaceholder: "Add details…",
    taskAssignee: "Assignee",
    taskDueDate: "Due date",
    taskStatus: "Status",
    taskPriority: "Priority",
    saveTask: "Save task",
    dropHere: "Drop tasks here",
    dragTask: "Drag to move task",
    addTask: "Add",
    taskTitlePlaceholder: "Task title…",
    deleteTask: "Delete task",
    confirmDeleteTask: "Delete this task? This cannot be undone.",
    deleteTaskError: "Failed to delete task. Please try again.",
    changeStatus: "Change status",
  },
  modal: {
    newProject: "New Project",
    editProject: "Edit Project",
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    titleLabel: "Project Title",
    descriptionLabel: "Description",
    statusLabel: "Status",
    technologiesLabel: "Technologies",
    semesterLabel: "Semester",
    yearLabel: "Year",
    startDateLabel: "Start date",
    endDateLabel: "End date",
    invalidDateRange: "End date must be on or after the start date.",
    repositoryLabel: "Repository URL",
    demoLabel: "Demo URL",
    visibilityLabel: "Visibility",
    titlePlaceholder: "Enter project title",
    descriptionPlaceholder: "Describe your project...",
    repositoryPlaceholder: "https://github.com/...",
    demoPlaceholder: "https://your-demo.com",
    membersLabel: "Team members",
    memberSearchPlaceholder: "Search by name or student ID…",
    noMembersFound: "No users match your search",
    memberOwner: "Owner",
  },
  admin: {
    title: "User management",
    subtitle: "Assign roles for system access control",
    searchPlaceholder: "Search by name, email, or student ID…",
    allRoles: "All roles",
    colName: "Name",
    colEmail: "Email",
    colStudentId: "Student ID",
    colRole: "Role",
    changeRole: "Change role for",
    noUsers: "No users match your filters.",
    loading: "Loading users…",
    you: "You",
    hint: "New accounts are created via sign-up or the Supabase dashboard. Role changes take effect on the user’s next request.",
    roleUpdateError:
      "Failed to update role. Ensure the admin RLS policy is applied.",
    colActions: "Actions",
    deleteAccount: "Delete account",
    confirmDeleteAccount: "Permanently delete {name} ({email})? This cannot be undone.",
    deleteAccountError:
      "Failed to delete account. Run supabase/admin_delete_user.sql in the SQL Editor.",
  },
  technologiesAdmin: {
    title: "Technology catalogue",
    subtitle: "Shared vocabulary used across all projects (SDCE)",
    searchPlaceholder: "Search technologies…",
    addTitle: "Add technology",
    editTitle: "Edit technology",
    colName: "Name",
    colCategory: "Category",
    colColor: "Color",
    namePlaceholder: "e.g. React",
    save: "Save",
    add: "Add",
    delete: "Delete",
    confirmDelete:
      "Remove this technology from the catalogue? Project links will be removed.",
    noMatch: "No technologies match your search.",
    loading: "Loading catalogue…",
    saveError: "Could not save technology. The name may already exist.",
    deleteError: "Could not delete technology.",
    categories: {
      language: "Language",
      framework: "Framework",
      tool: "Tool",
      database: "Database",
      cloud: "Cloud",
      other: "Other",
    },
  },
  team: {
    subtitle: "View and manage project teams",
    recentProjects: "Recent projects",
    selectProject: "Select a project…",
    searchProjects: "Search projects by name, description, or technology…",
    searchUsers: "Search by name, email or student ID…",
    noProjects: "No projects yet",
    noProjectsHint: "Join or create a project to see its team here",
    noMatch: "No projects match your search",
    member: "member",
    members: "members",
    selectHint: "Pick a recent project or search to get started",
    coordinator: "Coordinator",
    owner: "Owner",
    viewProject: "Open project",
    addMember: "Add member",
    addMemberHint:
      "Search for a student or staff member to add to this project.",
    removeMember: "Remove from project",
    confirmRemove: "Remove this member from the project?",
    addingMember: "Adding member…",
    readonlyHint:
      "You can view this team but only the owner, coordinator, or members (when no coordinator is assigned) can manage it.",
    emptyTeam: "No team members to display.",
    loading: "Loading team…",
  },
  browse: {
    title: "Academic Projects",
    subtitle: "Student Digital Career Ecosystem",
    searchPlaceholder: "Search projects or technologies…",
    viewDetails: "View details",
    viewDetailsCta: "View details →",
    signInCta: "Sign in",
    empty: "No public projects found.",
    loading: "Loading projects…",
    loadingProject: "Loading project…",
    footer: "Want to add your projects?",
    createAccount: "Create an account",
    member: "member",
    members: "members",
    backToProjects: "Back to projects",
    notFoundTitle: "Project not found",
    notFoundHint: "This project is private or does not exist.",
    backToBrowse: "← Back to browse",
    technologies: "Technologies",
    noTechnologies: "No technologies listed.",
    teamMembers: "Team members",
    tasksComplete: "Tasks complete",
    manageFooter: "Want to manage your own projects?",
    signInOrCreate: "Sign in or create an account",
  },
  profile: {
    loading: "Loading profile…",
    notFoundTitle: "User not found",
    notFoundHint: "This profile does not exist or you cannot view it.",
    goBack: "Go back",
    you: "You",
    mockupTitle: "Profile preview (mockup)",
    mockupBody:
      "This page shows only data stored in APMS. In a full SDCE deployment, skills, completed projects, certifications, and activity from other modules would appear here via REST APIs.",
    details: "Profile details",
    studentId: "Student ID",
    role: "Role",
    email: "Email",
    integrations: "SDCE integrations",
    eportfolioHint:
      "The e-Portfolio module would open this person’s public portfolio in a new tab.",
    eportfolioButton: "Open in e-Portfolio",
    eportfolioDisabledTitle: "Not connected in this mockup",
    eportfolioNote:
      "Button disabled — e-Portfolio integration is planned for a later release.",
    footerHint: "Find this person on",
    viewProfile: "View profile",
  },
  roles: {
    student: "Student",
    coordinator: "Coordinator",
    admin: "Administrator",
    guest: "Guest",
  },
};

export default strings;
