const strings = {
  appName: 'APMS',
  appFullName: 'Academic Project Management System',
  tagline: 'Organize · Track · Showcase',
  navbar: {
    toggleMenu: 'Toggle navigation menu',
    browse: 'Browse',
    dashboard: 'Dashboard',
    projects: 'Projects',
    kanban: 'Kanban',
    technologies: 'Technologies',
    team: 'Team',
    admin: 'Users',
    settings: 'Settings',
  },
  auth: {
    login: 'Sign In',
    logout: 'Sign Out',
    email: 'Email address',
    password: 'Password',
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in to your APMS account',
    demoAccounts: 'Demo accounts',
    loginError: 'Invalid email or password',
    domainNotAllowed: 'Only signups from the esg.ipsantarem.pt domain are allowed.',
    loginButton: 'Sign in',
    loggingIn: 'Signing in...',
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Overview of your academic projects',
    subtitleOverview: 'Overview of {n} projects you can access',
    totalProjects: 'Total Projects',
    activeProjects: 'Active Projects',
    completedProjects: 'Completed Projects',
    totalMembers: 'Team Members',
    recentProjects: 'Recent Projects',
    tasksByStatus: 'Tasks by Status',
    quickActions: 'Quick Actions',
    newProject: 'New Project',
    viewAll: 'View all',
  },
  projects: {
    title: 'Projects',
    subtitle: 'All academic projects',
    subtitleOverview: 'All accessible projects',
    new: 'New Project',
    search: 'Search projects...',
    filter: 'Filter',
    noProjects: 'No projects found',
    noProjectsHint: 'Create your first project to get started',
    status: {
      planning: 'Planning',
      active: 'Active',
      completed: 'Completed',
      archived: 'Archived',
    },
    sortBy: 'Sort by',
    allStatuses: 'All Statuses',
    viewDetails: 'View Details',
    editProject: 'Edit Project',
    deleteProject: 'Delete Project',
    confirmDelete: 'Are you sure you want to delete this project?',
    confirmDeleteAdmin: 'Delete this project permanently? All tasks and team links will be removed.',
    deleteError: 'Could not delete the project. You may not have permission.',
    tasks: 'Tasks',
    members: 'Members',
    technologies: 'Technologies',
    repository: 'Repository',
    demo: 'Live Demo',
    visibility: 'Visibility',
    public: 'Public',
    private: 'Private',
    semester: 'Semester',
    year: 'Year',
    timeline: 'Timeline',
    startDate: 'Start',
    endDate: 'End',
    created: 'Created',
    updated: 'Last updated',
  },
  kanban: {
    title: 'Kanban Board',
    subtitle: 'Manage project tasks',
    columns: {
      todo: 'To Do',
      'in-progress': 'In Progress',
      review: 'Review',
      done: 'Done',
    },
    noTasks: 'No tasks',
    priority: {
      low: 'Low',
      medium: 'Medium',
      high: 'High',
    },
    assignedTo: 'Assigned to',
    unassigned: 'Unassigned',
    due: 'Due',
    selectProject: 'Select a project to view its kanban board',
    editTask: 'Edit task',
    taskTitle: 'Title',
    taskDescription: 'Description',
    taskDescriptionPlaceholder: 'Add details…',
    taskAssignee: 'Assignee',
    taskDueDate: 'Due date',
    taskStatus: 'Status',
    taskPriority: 'Priority',
    saveTask: 'Save task',
    dropHere: 'Drop tasks here',
    addTask: 'Add',
    taskTitlePlaceholder: 'Task title…',
  },
  modal: {
    newProject: 'New Project',
    editProject: 'Edit Project',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    titleLabel: 'Project Title',
    descriptionLabel: 'Description',
    statusLabel: 'Status',
    technologiesLabel: 'Technologies',
    semesterLabel: 'Semester',
    yearLabel: 'Year',
    startDateLabel: 'Start date',
    endDateLabel: 'End date',
    invalidDateRange: 'End date must be on or after the start date.',
    repositoryLabel: 'Repository URL',
    demoLabel: 'Demo URL',
    visibilityLabel: 'Visibility',
    titlePlaceholder: 'Enter project title',
    descriptionPlaceholder: 'Describe your project...',
    repositoryPlaceholder: 'https://github.com/...',
    demoPlaceholder: 'https://your-demo.com',
  },
  admin: {
    title: 'User management',
    subtitle: 'Assign roles for system access control',
    searchPlaceholder: 'Search by name, email, or student ID…',
    allRoles: 'All roles',
    colName: 'Name',
    colEmail: 'Email',
    colStudentId: 'Student ID',
    colRole: 'Role',
    changeRole: 'Change role for',
    noUsers: 'No users match your filters.',
    loading: 'Loading users…',
    you: 'You',
    hint: 'New accounts are created via sign-up or the Supabase dashboard. Role changes take effect on the user’s next request.',
    roleUpdateError: 'Failed to update role. Ensure the admin RLS policy is applied.',
  },
  technologiesAdmin: {
    title: 'Technology catalogue',
    subtitle: 'Shared vocabulary used across all projects (SDCE)',
    searchPlaceholder: 'Search technologies…',
    addTitle: 'Add technology',
    editTitle: 'Edit technology',
    colName: 'Name',
    colCategory: 'Category',
    colColor: 'Color',
    namePlaceholder: 'e.g. React',
    save: 'Save',
    add: 'Add',
    delete: 'Delete',
    confirmDelete: 'Remove this technology from the catalogue? Project links will be removed.',
    noMatch: 'No technologies match your search.',
    loading: 'Loading catalogue…',
    saveError: 'Could not save technology. The name may already exist.',
    deleteError: 'Could not delete technology.',
    categories: {
      language: 'Language',
      framework: 'Framework',
      tool: 'Tool',
      database: 'Database',
      cloud: 'Cloud',
      other: 'Other',
    },
  },
  team: {
    subtitle: 'View members of your projects',
    selectProject: 'Select a project…',
    searchProjects: 'Search projects you can access…',
    noProjects: 'No projects yet',
    noProjectsHint: 'Join or create a project to see its team here',
    noMatch: 'No projects match your search',
    member: 'member',
    members: 'members',
    selectHint: 'Select a project to view its team members',
    coordinator: 'Coordinator',
    owner: 'Owner',
  },
  browse: {
    title: 'Academic Projects',
    subtitle: 'Student Digital Career Ecosystem',
    searchPlaceholder: 'Search projects or technologies…',
    viewDetails: 'View details',
    viewDetailsCta: 'View details →',
    signInCta: 'Sign in',
    empty: 'No public projects found.',
    loading: 'Loading projects…',
    loadingProject: 'Loading project…',
    footer: 'Want to add your projects?',
    createAccount: 'Create an account',
    member: 'member',
    members: 'members',
    backToProjects: 'Back to projects',
    notFoundTitle: 'Project not found',
    notFoundHint: 'This project is private or does not exist.',
    backToBrowse: '← Back to browse',
    technologies: 'Technologies',
    noTechnologies: 'No technologies listed.',
    teamMembers: 'Team members',
    tasksComplete: 'Tasks complete',
    manageFooter: 'Want to manage your own projects?',
    signInOrCreate: 'Sign in or create an account',
  },
  roles: {
    student: 'Student',
    coordinator: 'Coordinator',
    admin: 'Administrator',
    guest: 'Guest',
  },
};

export default strings;
