const strings = {
  appName: 'APMS',
  appFullName: 'Academic Project Management System',
  tagline: 'Organize · Track · Showcase',
  navbar: {
    toggleMenu: 'Toggle navigation menu',
    dashboard: 'Dashboard',
    projects: 'Projects',
    kanban: 'Kanban',
    technologies: 'Technologies',
    team: 'Team',
    settings: 'Settings',
  },
  auth: {
    login: 'Sign In',
    logout: 'Sign Out',
    email: 'Email address',
    password: 'Password',
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in to your APMS account',
    demoAccounts: 'Demo accounts',
    loginError: 'Invalid email or password',
    loginButton: 'Sign in',
    loggingIn: 'Signing in...',
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Overview of your academic projects',
    totalProjects: 'Total Projects',
    activeProjects: 'Active Projects',
    completedProjects: 'Completed Projects',
    totalMembers: 'Team Members',
    recentProjects: 'Recent Projects',
    tasksByStatus: 'Tasks by Status',
    quickActions: 'Quick Actions',
    newProject: 'New Project',
    viewAll: 'View all',
  },
  projects: {
    title: 'Projects',
    subtitle: 'All academic projects',
    new: 'New Project',
    search: 'Search projects...',
    filter: 'Filter',
    noProjects: 'No projects found',
    noProjectsHint: 'Create your first project to get started',
    status: {
      planning: 'Planning',
      active: 'Active',
      completed: 'Completed',
      archived: 'Archived',
    },
    sortBy: 'Sort by',
    allStatuses: 'All Statuses',
    viewDetails: 'View Details',
    editProject: 'Edit Project',
    deleteProject: 'Delete Project',
    confirmDelete: 'Are you sure you want to delete this project?',
    tasks: 'Tasks',
    members: 'Members',
    technologies: 'Technologies',
    repository: 'Repository',
    demo: 'Live Demo',
    visibility: 'Visibility',
    public: 'Public',
    private: 'Private',
    semester: 'Semester',
    year: 'Year',
    created: 'Created',
    updated: 'Last updated',
  },
  kanban: {
    title: 'Kanban Board',
    subtitle: 'Manage project tasks',
    columns: {
      todo: 'To Do',
      'in-progress': 'In Progress',
      review: 'Review',
      done: 'Done',
    },
    noTasks: 'No tasks',
    priority: {
      low: 'Low',
      medium: 'Medium',
      high: 'High',
    },
    assignedTo: 'Assigned to',
    unassigned: 'Unassigned',
    due: 'Due',
    selectProject: 'Select a project to view its kanban board',
  },
  modal: {
    newProject: 'New Project',
    editProject: 'Edit Project',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    titleLabel: 'Project Title',
    descriptionLabel: 'Description',
    statusLabel: 'Status',
    technologiesLabel: 'Technologies',
    semesterLabel: 'Semester',
    yearLabel: 'Year',
    repositoryLabel: 'Repository URL',
    demoLabel: 'Demo URL',
    visibilityLabel: 'Visibility',
    titlePlaceholder: 'Enter project title',
    descriptionPlaceholder: 'Describe your project...',
    repositoryPlaceholder: 'https://github.com/...',
    demoPlaceholder: 'https://your-demo.com',
  },
  roles: {
    student: 'Student',
    coordinator: 'Coordinator',
    admin: 'Administrator',
    guest: 'Guest',
  },
};

export default strings;
